### ISSUE TITLE
Unable to access the local url

### ISSUE THREAD

**Issue by iamrajee** [camenduru/gaussian-splatting-colab#5]
The URL http://0.0.0.0:7860/ shows nothing for me after running the viewer. But I can view it at the temporary Cloudflare URL
![image](https://github.com/camenduru/gaussian-splatting-colab/assets/25712145/d0fa1999-bf55-4d02-826d-818c09098c20)
![image](https://github.com/camenduru/gaussian-splatting-colab/assets/25712145/fcb999b1-5732-49b6-b32e-f1695b8ca4f2)
![image](https://github.com/camenduru/gaussian-splatting-colab/assets/25712145/435aef10-8fd1-45e0-80d8-d3c46479c4ac)

**Comment by EnesGumuskaynak** [comment]
Any update ?

**Comment by camenduru** [comment]
we cant see http://0.0.0.0:7860/ please use Cloudflare URL

**Comment by Golbstein** [comment]
what do you mean use Cloudflare URL?
I'm seeing this rendered train but I want to be able to view my scene
