### ISSUE TITLE
cuda version

### ISSUE THREAD

**Issue by msken** [camenduru/gaussian-splatting-colab#8]
When I tried train.py in gaussian_splatting_colab on colab, I got the following error message:

Traceback (most recent call last):
  File "/content/gaussian-splatting/train.py", line 16, in <module>
    from gaussian_renderer import render, network_gui
  File "/content/gaussian-splatting/gaussian_renderer/__init__.py", line 14, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
  File "/usr/local/lib/python3.10/dist-packages/diff_gaussian_rasterization/__init__.py", line 15, in <module>
    from . import _C
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

Actually, this worked fine a few days ago.

I checked the cuda version on the colab:
!nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0

I checked the possible selection of the cuda versions:
!ls -d /usr/local/cuda-*
/usr/local/cuda-12  /usr/local/cuda-12.2

I assume that the cause would be the mismatch of the cuda versions of submodules, and when I reinstall them, it worked fine now, but it took several minutes for reinstalling them.

!pip install -U submodules/diff-gaussian-rasterization
!pip install -U submodules/simple-knn

**Comment by fasteinke** [comment]
I also raised this issue ... and thanks for posting that workaround!

**Comment by NagaPadma** [comment]
> When I tried train.py in gaussian_splatting_colab on colab, I got the following error message:
> 
> Traceback (most recent call last): File "/content/gaussian-splatting/train.py", line 16, in from gaussian_renderer import render, network_gui File "/content/gaussian-splatting/gaussian_renderer/**init**.py", line 14, in from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer File "/usr/local/lib/python3.10/dist-packages/diff_gaussian_rasterization/**init**.py", line 15, in from . import _C ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
> 
> Actually, this worked fine a few days ago.
> 
> I checked the cuda version on the colab: !nvcc -V nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2023 NVIDIA Corporation Built on Tue_Aug_15_22:02:13_PDT_2023 Cuda compilation tools, release 12.2, V12.2.140 Build cuda_12.2.r12.2/compiler.33191640_0
> 
> I checked the possible selection of the cuda versions: !ls -d /usr/local/cuda-* /usr/local/cuda-12 /usr/local/cuda-12.2
> 
> I assume that the cause would be the mismatch of the cuda versions of submodules, and when I reinstall them, it worked fine now, but it took several minutes for reinstalling them.
> 
> !pip install -U submodules/diff-gaussian-rasterization !pip install -U submodules/simple-knn

thank you. reinstalling helped and resolved the issue. Thanks again.

**Comment by camenduru** [comment]
thanks ❤
